{% set version = "1.0.2" %}
{% set build = 0 %}

package:
  name: scikit-bio-binaries
  version: {{ version }}

source:
  url: https://github.com/scikit-bio/scikit-bio-binaries/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 64c392d5913813c31292655b82d5528a78fc3c677ba17c2e64ddb4b2c447ec25

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cuda-compiler # [linux and x86_64]
    - make
    - blas-devel
  host:
    - libcblas
    - liblapacke
  run:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - libcblas
    - liblapacke

test:
  commands:
    - test -f $PREFIX/include/scikit-bio-binaries/util.h
    - test -f $PREFIX/lib/libskbb.so

about:
  home: https://github.com/scikit-bio/scikit-bio-binaries
  summary: 'Optimized algorithms for bioinformatics in support of scikit-bio'
  description: |
    scikit-bio-binaries is an open-source, BSD-licensed package providing optimized algorithms
    for bioinformatics in support of scikit-bio.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/scikit-bio/scikit-bio-binaries

extra:
  recipe-maintainers:
    - sfiligoi
