build_platform:
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
    linux_86: default
    linux_aarch64: default
    osx_86: default
    win_86: None
